CREATE DATABASE VENTASBD;

USE VENTASBD;
GO

CREATE TABLE CONFIGURACIONES (
    IDCONFIGURACION INT NOT NULL,
    TASAFINANCIAMIENTO FLOAT NOT NULL,
    PORCENTAJENGANCHE FLOAT NOT NULL,
    PLAZOMAXIMO INT NOT NULL,
    CONSTRAINT PK_IDCONFIGURACION_CONFIGURACIONES PRIMARY KEY(IDCONFIGURACION),
);

CREATE TABLE CLIENTES (
    IDCLIENTE INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOPATERNO VARCHAR(50) NOT NULL,
    APELLIDOMATERNO VARCHAR(50) NOT NULL,
    RFC VARCHAR(15) NOT NULL,
    FECHA DATE NOT NULL,
    ESTATUS VARCHAR(9) NOT NULL,
    CONSTRAINT PK_IDCLIENTE_CLIENTES PRIMARY KEY(IDCLIENTE),
    CONSTRAINT CONSTRAINT_ESTATUS_CLIENTES CHECK (ESTATUS = 'Activo' OR ESTATUS = 'Cancelado')
);

CREATE TABLE ARTICULOS (
    IDARTICULO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,    
    EXISTENCIA FLOAT NOT NULL,
    PRECIO FLOAT NOT NULL,
    FECHA DATE NOT NULL,
    ESTATUS VARCHAR(9) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_IDARTICULO_ARTICULOS PRIMARY KEY(IDARTICULO),
    CONSTRAINT CONSTRAINT_ESTATUS_ARTICULOS CHECK (ESTATUS = 'Activo' OR ESTATUS = 'Cancelado')
);

CREATE TABLE VENTAS (
    IDVENTA INT NOT NULL,
    IDCLIENTE INT NOT NULL,
    ENGANCHE FLOAT NOT NULL,
    BONIFICACIONENGANCHE FLOAT NOT NULL,
    TOTALADEUDO FLOAT NOT NULL,
    TOTALPAGAR FLOAT NOT NULL,
    PRECIOCONTADO FLOAT NOT NULL,
    IMPORTEABONO FLOAT NOT NULL,
    IMPORTEAHORRO FLOAT NOT NULL,
    PLAZOPAGO INT NOT NULL,
    FECHA DATE NOT NULL,
    ESTATUS VARCHAR(9) NOT NULL,
    CONSTRAINT PK_IDVENTA_VENTAS PRIMARY KEY(IDVENTA),
    CONSTRAINT FK_IDCLIENTE_VENTAS FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE),
    CONSTRAINT CONSTRAINT_ESTATUS_VENTAS CHECK (ESTATUS = 'Activo' OR ESTATUS = 'Cancelado'),
    CONSTRAINT CONSTRAINT_PLAZOPAGO_VENTAS CHECK (PLAZOPAGO = 3 OR PLAZOPAGO = 6 OR PLAZOPAGO = 9 OR PLAZOPAGO = 12)
);

CREATE TABLE VENTASDETALLE (
    IDVENTA INT NOT NULL,
    IDDETALLE INT NOT NULL,
    IDARTICULO VARCHAR(10) NOT NULL,
    CANTIDAD FLOAT NOT NULL,
    PRECIO FLOAT NOT NULL,
    IMPORTE FLOAT NOT NULL,
    ESTATUS VARCHAR(9) NOT NULL,
    CONSTRAINT PK_IDDETALLE_VENTASDETALLE PRIMARY KEY(IDVENTA, IDDETALLE),
    CONSTRAINT FK_IDARTICULO_VENTASDETALLE FOREIGN KEY (IDARTICULO) REFERENCES ARTICULOS(IDARTICULO),
    CONSTRAINT CONSTRAINT_ESTATUS_VENTASDETALLE CHECK (ESTATUS = 'Activo' OR ESTATUS = 'Cancelado')
);

USE VENTASBD
GO
CREATE PROCEDURE SP_DISMINUIR_EXISTENCIA_ARTICULO
    @IDARTICULO nvarchar(10),
    @EXISTENCIA FLOAT
AS
    UPDATE ARTICULOS SET EXISTENCIA = (EXISTENCIA - @EXISTENCIA)
    WHERE IDARTICULO = @IDARTICULO
GO

USE VENTASBD
GO
CREATE PROCEDURE SP_AUMENTAR_EXISTENCIA_ARTICULO
    @IDARTICULO nvarchar(10),
    @EXISTENCIA FLOAT
AS
    UPDATE ARTICULOS SET EXISTENCIA = (EXISTENCIA + @EXISTENCIA)
    WHERE IDARTICULO = @IDARTICULO
GO

USE VENTASBD
GO
CREATE PROCEDURE SP_ULTIMO_CLIENTE
    @IDCLIENTE INT
AS
    SET @IDCLIENTE = (SELECT (COALESCE(MAX(IDCLIENTE), 0) + 1) FROM CLIENTES)
    SELECT @IDCLIENTE
GO

USE VENTASBD
GO
CREATE PROCEDURE SP_ULTIMO_VENTAS
    @IDVENTA INT
AS
    SET @IDVENTA = (SELECT (COALESCE(MAX(IDVENTA), 0) + 1) FROM VENTAS)
    SELECT @IDVENTA
GO

USE VENTASBD;

INSERT INTO CONFIGURACIONES ([IDCONFIGURACION], [TASAFINANCIAMIENTO], [PORCENTAJENGANCHE], [PLAZOMAXIMO])
VALUES (1, 2.8, 20, 12)

INSERT INTO CLIENTES ([IDCLIENTE], [NOMBRE], [APELLIDOPATERNO], [APELLIDOMATERNO], [RFC], [FECHA], [ESTATUS])
VALUES (1, 'Juan', 'Perez', 'Mercado', 'MEPEJ831209-RL1', '2017-11-19', 'Activo')
INSERT INTO CLIENTES ([IDCLIENTE], [NOMBRE], [APELLIDOPATERNO], [APELLIDOMATERNO], [RFC], [FECHA], [ESTATUS])
VALUES (2, 'Irma', 'Aguilar', 'Dorantes', 'DOIA000220NB0', '2017-02-20', 'Activo')
INSERT INTO CLIENTES ([IDCLIENTE], [NOMBRE], [APELLIDOPATERNO], [APELLIDOMATERNO], [RFC], [FECHA], [ESTATUS])
VALUES (3, 'Julio Eduardo', 'Díaz', 'Sánchez', 'DASJ880731KE6', '2017-07-31', 'Cancelado')

INSERT INTO ARTICULOS ([IDARTICULO], [DESCRIPCION], [EXISTENCIA], [PRECIO], [FECHA], [ESTATUS], [MODELO])
VALUES ('CMMB-1M6S', 'Comedor Marmol 6 Sillas', 27, 4250, '2017-05-15', 'Activo', 'Morgan Blanco')
INSERT INTO ARTICULOS ([IDARTICULO], [DESCRIPCION], [EXISTENCIA], [PRECIO], [FECHA], [ESTATUS], [MODELO])
VALUES ('COMVAL-4S', 'Comedor con 4 Sillas', 35, 4250, '2017-04-01', 'Activo', 'Valencia')
INSERT INTO ARTICULOS ([IDARTICULO], [DESCRIPCION], [EXISTENCIA], [PRECIO], [FECHA], [ESTATUS], [MODELO])
VALUES ('SALACS-22', 'Sala Contemporánea en Suede', 0, 9499, '2017-12-07', 'Activo', 'Sicilia')
INSERT INTO ARTICULOS ([IDARTICULO], [DESCRIPCION], [EXISTENCIA], [PRECIO], [FECHA], [ESTATUS], [MODELO])
VALUES ('COMMON-6S', 'Comedor con 6 Sillas', 48, 11856, '2017-03-09', 'Activo', 'Monserrat')